# pandas.DataFrame.to_numpy
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html

In [1]:
import numpy as np
import pandas as pd

## 1. pandas.DataFrame.values
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html

In [2]:
df = pd.DataFrame({'age':    [ 3,  29],
                   'height': [94, 170],
                   'weight': [31, 115]})
df

age  height  weight
0    3      94      31
1   29     170     115

In [3]:
df.dtypes

age       int64
height    int64
weight    int64
dtype: object

In [4]:
df.values

array([[  3,  94,  31],
       [ 29, 170, 115]])

In [5]:
df.values[0][2]

31

In [6]:
df2 = pd.DataFrame([('parrot',   24.0, 'second'),
                    ('lion',     80.5, 1),
                    ('monkey', np.nan, None)],
                  columns=('name', 'max_speed', 'rank'))
df2

name  max_speed    rank
0  parrot       24.0  second
1    lion       80.5       1
2  monkey        NaN    None

In [7]:
df2.dtypes

name          object
max_speed    float64
rank          object
dtype: object

In [8]:
df2.values

array([['parrot', 24.0, 'second'],
       ['lion', 80.5, 1],
       ['monkey', nan, None]], dtype=object)

In [9]:
df2.values[2][0]

'monkey'

### 1-1. Test by myself

In [10]:
df3 = pd.DataFrame({1: [11, 111],
                    2: [22, 222],
                    3: [33, 333]})
df3

1    2    3
0   11   22   33
1  111  222  333

In [11]:
df3.dtypes

1    int64
2    int64
3    int64
dtype: object

## 2. pandas.DataFrame.to_numpy
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy

In [14]:
df4 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df4

A  B
0  1  3
1  2  4

In [15]:
pd.DataFrame({"A": [1, 2], "B": [3, 4]}).to_numpy()

array([[1, 3],
       [2, 4]])

In [16]:
pd.DataFrame({"A": [1, 2], "B": [3, 4]}).to_numpy().dtype

dtype('int64')

In [18]:
df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.5]})
df

A    B
0  1  3.0
1  2  4.5

In [19]:
df.to_numpy()

array([[1. , 3. ],
       [2. , 4.5]])

In [20]:
df.to_numpy().dtype

dtype('float64')

In [21]:
df['C'] = pd.date_range('2000', periods=2)
df

A    B          C
0  1  3.0 2000-01-01
1  2  4.5 2000-01-02

In [22]:
df.to_numpy()

array([[1, 3.0, Timestamp('2000-01-01 00:00:00')],
       [2, 4.5, Timestamp('2000-01-02 00:00:00')]], dtype=object)

In [23]:
df.to_numpy().dtype

dtype('O')

### 2-1. Test by myself

In [30]:
df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.5]})
df

A    B
0  1  3.0
1  2  4.5

In [31]:
df.dtypes

A      int64
B    float64
dtype: object

In [32]:
nparray_df = df.to_numpy()
nparray_df

array([[1. , 3. ],
       [2. , 4.5]])

In [33]:
nparray_df.dtype

dtype('float64')

In [34]:
nparray_df_f32 = df.to_numpy(dtype='float32')
nparray_df_f32

array([[1. , 3. ],
       [2. , 4.5]], dtype=float32)

In [35]:
nparray_df_f32.dtype

dtype('float32')