# pandas-2
https://ithelp.ithome.com.tw/users/20107514/ironman/1399?page=1

## 1. [Day06]Pandas的兩種資料類型
https://ithelp.ithome.com.tw/articles/10193394  
Two particular data structure are `DataFrame` and `Series`, respectively.

In [1]:
import pandas as pd
import numpy as np

### A.

In [2]:
pd.__version__

'1.1.4'

In [4]:
my_obj = pd.Series([4, 7, -5, 3])
my_obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
my_obj.values

array([ 4,  7, -5,  3])

In [6]:
my_obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
my_obj2 = pd.Series([8,9,10,11], index=['a','b','c','d'])
my_obj2

a     8
b     9
c    10
d    11
dtype: int64

In [11]:
my_obj2.values

array([ 8,  9, 10, 11])

In [12]:
my_obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
my_obj2['a']

8

In [14]:
'a' in my_obj2

True

In [15]:
'a' in my_obj

False

In [21]:
my_obj2_own = pd.Series({'a':8,'b':9,'c':10,'d':11})
my_obj2_own

a     8
b     9
c    10
d    11
dtype: int64

### B.

In [17]:
dic_data = {'name':'apple','birthday':'1996-1-1','luckynumber':7 }
dic_data

{'name': 'apple', 'birthday': '1996-1-1', 'luckynumber': 7}

In [19]:
my_obj3 = pd.Series(dic_data)
my_obj3

name              apple
birthday       1996-1-1
luckynumber           7
dtype: object

In [20]:
registration = [True,False,True,True]
registration = pd.Series(registration)
registration

0     True
1    False
2     True
3     True
dtype: bool

In [22]:
dictionary = {'A':'an animal',
              'B':'a color',
              'C':'a fruit'}
dictionary = pd.Series(dictionary)
dictionary

A    an animal
B      a color
C      a fruit
dtype: object

### <font color=red> C. Important </font>

In [23]:
data = {'name': ['Bob', 'Nancy','Amy','Elsa','Jack'],
        'year': [1996, 1997, 1997, 1996, 1997],
        'month': [8, 8, 7, 1, 12],
        'day':[11,23,8,3,11]}
myframe = pd.DataFrame(data)
myframe

name  year  month  day
0    Bob  1996      8   11
1  Nancy  1997      8   23
2    Amy  1997      7    8
3   Elsa  1996      1    3
4   Jack  1997     12   11

In [26]:
myframe2 = pd.DataFrame(data,columns=['name', 'month', 'day', 'year'])
myframe2

name  month  day  year
0    Bob      8   11  1996
1  Nancy      8   23  1997
2    Amy      7    8  1997
3   Elsa      1    3  1996
4   Jack     12   11  1997

In [27]:
myframe3 = pd.DataFrame(data,columns=['name','year', 'month', 'day','luckynumber'])
myframe3

name  year  month  day luckynumber
0    Bob  1996      8   11         NaN
1  Nancy  1997      8   23         NaN
2    Amy  1997      7    8         NaN
3   Elsa  1996      1    3         NaN
4   Jack  1997     12   11         NaN

In [29]:
luckynumber = ['3','2','1','7','8']
luckynumber = pd.Series(luckynumber)
luckynumber

0    3
1    2
2    1
3    7
4    8
dtype: object

In [31]:
myframe3['luckynumber'] = luckynumber
myframe3

name  year  month  day luckynumber
0    Bob  1996      8   11           3
1  Nancy  1997      8   23           2
2    Amy  1997      7    8           1
3   Elsa  1996      1    3           7
4   Jack  1997     12   11           8

In [33]:
myframe3['2']

KeyError: '2'

In [34]:
myframe3['year']

0    1996
1    1997
2    1997
3    1996
4    1997
Name: year, dtype: int64

In [36]:
myframe3['year']+10

0    2006
1    2007
2    2007
3    2006
4    2007
Name: year, dtype: int64

## 2. [Day07]Pandas 操作資料的函數
https://ithelp.ithome.com.tw/articles/10193421

In [1]:
import pandas as pd

In [2]:
# df = pd.read_csv('./csv檔案位置')

data = {'Name': ['Avery Bradley', 'Jae Crowder','John Holland','R.J. Hunter','Jonas Jerebko'],
        'Team': ['Boston Celtics', 'Boston Celtics', 'Boston Celtics', 'Boston Celtics', 'Boston Celtics'],
        'Number': [0.0, 99.0, 30.0, 28.0, 8.0],
        'Position': ['PG', 'SF', 'SG', 'SG', 'PF'],
        'Age': [25.0, 25.0, 27.0, 22.0, 29.0],
        'Height': ['6-2', '6-6', '6-5', '6-5', '6-10'],
        'Weight': [180.0, 235.0, 205.0, 185.0, 231.0],
        'College': ['Texas', 'Marquette', 'Boston University', 'Georgia State', 'NaN'],
        'Salary':[7730337.0,6796117.0,'NaN',1148640.0,5000000.0]}
df = pd.DataFrame(data)
df

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College       Salary  
0              Texas  7.73034e+06  
1          Marquette  6.79612e+06  
2  Boston University          NaN  
3      Georgia State  1.14864e+06  
4                NaN        5e+06

In [3]:
df.head(2)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   

     College       Salary  
0      Texas  7.73034e+06  
1  Marquette  6.79612e+06

In [4]:
df.tail(3)

Name            Team  Number Position   Age Height  Weight  \
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College       Salary  
2  Boston University          NaN  
3      Georgia State  1.14864e+06  
4                NaN        5e+06

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      5 non-null      object 
 1   Team      5 non-null      object 
 2   Number    5 non-null      float64
 3   Position  5 non-null      object 
 4   Age       5 non-null      float64
 5   Height    5 non-null      object 
 6   Weight    5 non-null      float64
 7   College   5 non-null      object 
 8   Salary    5 non-null      object 
dtypes: float64(3), object(6)
memory usage: 488.0+ bytes


In [6]:
df.shape

(5, 9)

In [7]:
df['Name']

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

In [8]:
df['Name'][0:4]

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
Name: Name, dtype: object

In [9]:
df[['Name','Team']]

Name            Team
0  Avery Bradley  Boston Celtics
1    Jae Crowder  Boston Celtics
2   John Holland  Boston Celtics
3    R.J. Hunter  Boston Celtics
4  Jonas Jerebko  Boston Celtics

In [10]:
df[['Name'],['Team']]

TypeError: '(['Name'], ['Team'])' is an invalid key

In [11]:
df['Name','Team']

KeyError: ('Name', 'Team')

In [10]:
df.insert(3,column="sport",value="Basketball")
df

Name            Team  Number       sport Position   Age Height  \
0  Avery Bradley  Boston Celtics     0.0  Basketball       PG  25.0    6-2   
1    Jae Crowder  Boston Celtics    99.0  Basketball       SF  25.0    6-6   
2   John Holland  Boston Celtics    30.0  Basketball       SG  27.0    6-5   
3    R.J. Hunter  Boston Celtics    28.0  Basketball       SG  22.0    6-5   
4  Jonas Jerebko  Boston Celtics     8.0  Basketball       PF  29.0   6-10   

   Weight            College       Salary  
0   180.0              Texas  7.73034e+06  
1   235.0          Marquette  6.79612e+06  
2   205.0  Boston University          NaN  
3   185.0      Georgia State  1.14864e+06  
4   231.0                NaN        5e+06

In [11]:
df.fillna(0)

Name            Team  Number       sport Position   Age Height  \
0  Avery Bradley  Boston Celtics     0.0  Basketball       PG  25.0    6-2   
1    Jae Crowder  Boston Celtics    99.0  Basketball       SF  25.0    6-6   
2   John Holland  Boston Celtics    30.0  Basketball       SG  27.0    6-5   
3    R.J. Hunter  Boston Celtics    28.0  Basketball       SG  22.0    6-5   
4  Jonas Jerebko  Boston Celtics     8.0  Basketball       PF  29.0   6-10   

   Weight            College       Salary  
0   180.0              Texas  7.73034e+06  
1   235.0          Marquette  6.79612e+06  
2   205.0  Boston University          NaN  
3   185.0      Georgia State  1.14864e+06  
4   231.0                NaN        5e+06

In [12]:
df.sort_values("Name")

Name            Team  Number       sport Position   Age Height  \
0  Avery Bradley  Boston Celtics     0.0  Basketball       PG  25.0    6-2   
1    Jae Crowder  Boston Celtics    99.0  Basketball       SF  25.0    6-6   
2   John Holland  Boston Celtics    30.0  Basketball       SG  27.0    6-5   
4  Jonas Jerebko  Boston Celtics     8.0  Basketball       PF  29.0   6-10   
3    R.J. Hunter  Boston Celtics    28.0  Basketball       SG  22.0    6-5   

   Weight            College       Salary  
0   180.0              Texas  7.73034e+06  
1   235.0          Marquette  6.79612e+06  
2   205.0  Boston University          NaN  
4   231.0                NaN        5e+06  
3   185.0      Georgia State  1.14864e+06

## [Day08]Pandas資料的取得與篩選
https://ithelp.ithome.com.tw/articles/10194003

In [1]:
import pandas as pd

In [2]:
seriesObj = pd.Series(range(10),index=['a', 'a', 'b', 'b', 'b','c','c','c','c','c'])
seriesObj

a    0
a    1
b    2
b    3
b    4
c    5
c    6
c    7
c    8
c    9
dtype: int64

In [3]:
seriesObj['c']

c    5
c    6
c    7
c    8
c    9
dtype: int64

In [7]:
np.random.randn(4,2)

array([[-0.33829245, -0.91374548],
       [ 0.75472324,  0.53883982],
       [ 1.65208843, -0.25783867],
       [-0.74268303, -0.30506774]])

In [8]:
print(np.random.randn(4,2))

[[ 0.70997331  0.33538575]
 [ 0.3927473   2.05057154]
 [-0.67631785  0.72846702]
 [ 1.61092836 -0.10753066]]


In [4]:
import numpy as np
df = pd.DataFrame(np.random.randn(4,2),index=['a', 'a', 'b', 'b'])
df

0         1
a -0.317409 -0.775007
a  0.296054  1.123482
b  0.876793 -0.103041
b -1.504266  1.520650

In [9]:
df.ix['b']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [10]:
df.loc['b']

0         1
b  0.876793 -0.103041
b -1.504266  1.520650

## [Day09]Pandas索引的運用
https://ithelp.ithome.com.tw/articles/10194006