# numpy.append
https://numpy.org/doc/stable/reference/generated/numpy.append.html

## 1. https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [2]:
import numpy as np

In [3]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### 1-1. Own test

In [10]:
np.append([1, 2, 3], [4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [11]:
np.append([1, 2, 3], [4, 5, 6], [7, 8, 9])

TypeError: 'list' object cannot be interpreted as an integer