# numpy.argsort
https://numpy.org/doc/stable/reference/generated/numpy.argsort.html#numpy.argsort

## 1. https://numpy.org/doc/stable/reference/generated/numpy.argsort.html#numpy.argsort

In [2]:
import numpy as np

### 1-1. One dimensional array

In [3]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

### 1-2. Two-dimensional array

In [4]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [5]:
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
ind

array([[0, 1],
       [1, 0]])

In [6]:
np.take_along_axis(x, ind, axis=0)  # same as np.sort(x, axis=0)

array([[0, 2],
       [2, 3]])

In [7]:
ind = np.argsort(x, axis=1)  # sorts along last axis (across)
ind

array([[0, 1],
       [0, 1]])

In [8]:
np.take_along_axis(x, ind, axis=1)  # same as np.sort(x, axis=1)

array([[0, 3],
       [2, 2]])

### 1-3. N-dimensional array

In [9]:
ind = np.unravel_index(np.argsort(x, axis=None), x.shape)
ind

(array([0, 1, 1, 0]), array([0, 0, 1, 1]))

In [10]:
x[ind]  # same as np.sort(x, axis=None)

array([0, 2, 2, 3])

### 1-4. Sorting with keays

In [11]:
x = np.array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])
x

array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])

In [14]:
x[0]

(1, 0)

In [15]:
np.argsort(x, order=('x','y'))

array([1, 0])

In [16]:
np.argsort(x, order=('y','x'))

array([0, 1])

In [18]:
x[0].x

AttributeError: 'numpy.void' object has no attribute 'x'

## 2. By Myself

In [19]:
# 5 -> 2 -> 3 -> 1 -> 4 -> 6 -> 0
x = np.array([10, 3, 1, 2, 6, 0, 7])
np.argsort(x)

array([5, 2, 3, 1, 4, 6, 0])

In [20]:
np.argsort(x)[0]

5

In [21]:
np.argsort(x)[1]

2

In [22]:
np.argsort(x)[6]

0