# numpy.concatenate
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

## 1. https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [4]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [5]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 1-1. 1 dimension

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate((x,y),axis=None)

array([1, 2, 3, 4, 5, 6])

In [7]:
np.concatenate((x,y),axis=0)

array([1, 2, 3, 4, 5, 6])

In [8]:
np.concatenate((x,y),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [9]:
np.concatenate((x,y),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 1

### 1-2. 1 and 2 dimensions

In [10]:
x = np.array([[1,2,3]])
y = np.array([4,5,6])
np.concatenate((x,y),axis=None)

array([1, 2, 3, 4, 5, 6])

In [11]:
np.concatenate((x,y),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### 1-3. 2 dimensions

In [12]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
np.concatenate((x,y),axis=None)

array([1, 2, 3, 4, 5, 6])

In [13]:
np.concatenate((x,y),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.concatenate((x,y),axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [15]:
np.concatenate((x,y),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

### 1-4. 3 lists

In [16]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
np.concatenate((x,y,z),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. https://blog.csdn.net/qq_39516859/article/details/80666070

#### Note: np.append() is flexible, but there is a larger temporary storage. np.concatenate() has no this problem.

## 3. https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/568147/