# numpy.core.records.fromarrays
https://numpy.org/doc/stable/reference/generated/numpy.core.records.fromarrays.html

In [1]:
import numpy as np

## 1. Examples

### 1-1. Examples 1

In [2]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])

(2, 'dd', 2.)


In [3]:
r

rec.array([(1, 'a', 1.1), (2, 'dd', 2. ), (3, 'xyz', 3. ), (4, '12', 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8')])

In [4]:
x1[1]=34

In [5]:
x1

array([ 1, 34,  3,  4])

In [6]:
r

rec.array([(1, 'a', 1.1), (2, 'dd', 2. ), (3, 'xyz', 3. ), (4, '12', 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8')])

In [7]:
r.a

array([1, 2, 3, 4])

In [8]:
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
r

rec.array([( 1, 'a', 1.1), (34, 'dd', 2. ), ( 3, 'xyz', 3. ),
           ( 4, '12', 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8')])

### 1-2. Exaples 2

In [9]:
x1 = np.array([1, 2, 3, 4])
x2 = np.array(['a', 'dd', 'xyz', '12'])
x3 = np.array([1.1, 2, 3,4])
r = np.core.records.fromarrays(
    [x1, x2, x3],
    dtype=np.dtype([('a', np.int32), ('b', 'S3'), ('c', np.float32)]))
r

rec.array([(1, b'a', 1.1), (2, b'dd', 2. ), (3, b'xyz', 3. ),
           (4, b'12', 4. )],
          dtype=[('a', '<i4'), ('b', 'S3'), ('c', '<f4')])

In [10]:
r.b

array([b'a', b'dd', b'xyz', b'12'], dtype='|S3')

In [11]:
r[2]

(3, b'xyz', 3.)

### 1-3. Test by myself

In [12]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x1x2x3 = np.array([x1, x2, x3])
x1x2x3

array([['1', '2', '3', '4'],
       ['a', 'dd', 'xyz', '12'],
       ['1.1', '2.0', '3.0', '4.0']], dtype='<U32')

In [13]:
print(x1x2x3)

[['1' '2' '3' '4']
 ['a' 'dd' 'xyz' '12']
 ['1.1' '2.0' '3.0' '4.0']]


In [14]:
r_x1x2x3 = np.core.records.fromarrays(x1x2x3, names='a,b,c')
print(r_x1x2x3[1])

('2', 'dd', '2.0')


In [15]:
r_x1x2x3

rec.array([('1', 'a', '1.1'), ('2', 'dd', '2.0'), ('3', 'xyz', '3.0'),
           ('4', '12', '4.0')],
          dtype=[('a', '<U32'), ('b', '<U32'), ('c', '<U32')])

#### Conclusion: Take care the dtype.

In [16]:
r_x1x2x3_dtype = np.core.records.fromarrays(x1x2x3, dtype=np.dtype([('a', np.int32), ('b', 'S3'), ('c', np.float32)]))
print(r[1])

(2, b'dd', 2.)


In [17]:
r_x1x2x3_dtype

rec.array([(1, b'a', 1.1), (2, b'dd', 2. ), (3, b'xyz', 3. ),
           (4, b'12', 4. )],
          dtype=[('a', '<i4'), ('b', 'S3'), ('c', '<f4')])

In [18]:
r_x1x2x3_dtype.a-r.a

array([0, 0, 0, 0], dtype=int32)

In [19]:
r_x1x2x3_dtype.b-r.b

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('S3'), dtype('S3')) -> dtype('S3')

In [20]:
r_x1x2x3_dtype.c-r.c

array([0., 0., 0., 0.], dtype=float32)

#### Conclusion: If we combine all np.array() into a np.array(), have to use dtype or name & formats.

In [21]:
x1 = np.array([1, 2, 3, 4])
x2 = np.array([6.9, 7.8, 8.7, 9.6])
x3 = np.array([1.1, 2, 3,4])
r = np.core.records.fromarrays(
    [x1, x2, x3],
    dtype=np.dtype([('a', np.int32), ('b', np.float64), ('c', np.float32)]))
r

rec.array([(1, 6.9, 1.1), (2, 7.8, 2. ), (3, 8.7, 3. ), (4, 9.6, 4. )],
          dtype=[('a', '<i4'), ('b', '<f8'), ('c', '<f4')])

In [22]:
x1x2x3 = np.array([x1, x2, x3])
x1x2x3

array([[1. , 2. , 3. , 4. ],
       [6.9, 7.8, 8.7, 9.6],
       [1.1, 2. , 3. , 4. ]])

In [23]:
r_x1x2x3 = np.core.records.fromarrays(x1x2x3, dtype=np.dtype([('a', np.int32), ('b', np.float64), ('c', np.float32)]))
r_x1x2x3

rec.array([(1, 6.9, 1.1), (2, 7.8, 2. ), (3, 8.7, 3. ), (4, 9.6, 4. )],
          dtype=[('a', '<i4'), ('b', '<f8'), ('c', '<f4')])

In [24]:
r_x1x2x3.a-r.a

array([0, 0, 0, 0], dtype=int32)

In [25]:
r_x1x2x3.b-r.b

array([0., 0., 0., 0.])

In [26]:
r_x1x2x3.c-r.c

array([0., 0., 0., 0.], dtype=float32)

#### Conclusion: We have to use dtype to make sure every type is the same.