# numpy.savez and numpy.savez_compressed
https://numpy.org/doc/stable/reference/generated/numpy.savez.html

In [1]:
import numpy as np

## 1. NumPy
https://numpy.org/doc/stable/reference/generated/numpy.savez.html

### 1-1. numpy.savez()

In [42]:
from tempfile import TemporaryFile
outfile = TemporaryFile()
x = np.arange(10)
y = np.sin(x)

In [43]:
outfile

<_io.BufferedRandom name=65>

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
y

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [46]:
np.savez(outfile, x, y)
_ = outfile.seek(0) # Only needed here to simulate closing & reopening file
npzfile = np.load(outfile)
npzfile.files

['arr_0', 'arr_1']

In [47]:
print(npzfile['arr_0'] - x)
npzfile['arr_0']

[0 0 0 0 0 0 0 0 0 0]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
print(npzfile['arr_1'] - y)
npzfile['arr_1']

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [49]:
outfile = TemporaryFile()
np.savez(outfile, x=x, y=y)
_ = outfile.seek(0)
npzfile = np.load(outfile)
sorted(npzfile.files)

['x', 'y']

In [50]:
npzfile.files

['x', 'y']

In [53]:
print(npzfile['x'] - x)
npzfile['x']

[0 0 0 0 0 0 0 0 0 0]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
print(npzfile['y'] - y)
npzfile['y']

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### 1-2. numpy.savez_compressed

In [55]:
test_array = np.random.rand(3, 2)
test_vector = np.random.rand(4)
np.savez_compressed('/tmp/123', a=test_array, b=test_vector)
loaded = np.load('/tmp/123.npz')
print(np.array_equal(test_array, loaded['a']))

True


In [56]:
test_array

array([[0.18376609, 0.65183455],
       [0.84047194, 0.44472963],
       [0.2516034 , 0.04812603]])

In [57]:
test_vector

array([0.76680643, 0.40547719, 0.44674704, 0.48756472])

In [58]:
loaded.files

['a', 'b']

In [59]:
print(np.array_equal(test_vector, loaded['b']))

True


In [60]:
print(loaded['a'] - test_array)
loaded['a']

[[0. 0.]
 [0. 0.]
 [0. 0.]]


array([[0.18376609, 0.65183455],
       [0.84047194, 0.44472963],
       [0.2516034 , 0.04812603]])

In [61]:
print(loaded['b'] - test_vector)
loaded['b']

[0. 0. 0. 0.]


array([0.76680643, 0.40547719, 0.44674704, 0.48756472])

## 2. Numpy 筆記-#02 另存變數為 .npz
https://www.brilliantcode.net/1832/numpy-note-02-save-variables-as-npz/

In [2]:
arr1 = np.arange(1, 101).reshape(10, 10)
arr2 = np.arange(1, 10001).reshape(100, 100)
arr3 = np.arange(1, 1000001).reshape(1000, 1000)

In [7]:
print(arr1.shape)
arr1

(10, 10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [8]:
print(arr2.shape)
arr2

(100, 100)


array([[    1,     2,     3, ...,    98,    99,   100],
       [  101,   102,   103, ...,   198,   199,   200],
       [  201,   202,   203, ...,   298,   299,   300],
       ...,
       [ 9701,  9702,  9703, ...,  9798,  9799,  9800],
       [ 9801,  9802,  9803, ...,  9898,  9899,  9900],
       [ 9901,  9902,  9903, ...,  9998,  9999, 10000]])

In [9]:
print(arr3.shape)
arr3

(1000, 1000)


array([[      1,       2,       3, ...,     998,     999,    1000],
       [   1001,    1002,    1003, ...,    1998,    1999,    2000],
       [   2001,    2002,    2003, ...,    2998,    2999,    3000],
       ...,
       [ 997001,  997002,  997003, ...,  997998,  997999,  998000],
       [ 998001,  998002,  998003, ...,  998998,  998999,  999000],
       [ 999001,  999002,  999003, ...,  999998,  999999, 1000000]])

In [10]:
np.savez('example_savez.npz', my_arr1=arr1, my_arr2=arr2, my_arr3=arr3)

In [11]:
arr4 = np.arange(1, 101).reshape(10, 10)
arr5 = np.arange(1, 10001).reshape(100, 100)
arr6 = np.arange(1, 1000001).reshape(1000, 1000)

np.savez_compressed('example_savez_compressed.npz', my_arr4=arr4, my_arr5=arr5, my_arr6=arr6)

In [12]:
npz_file = np.load('example_savez_compressed.npz')
new_arr4, new_arr5 = npz_file['my_arr4'], npz_file['my_arr5']

print('Shape of new_arr4: {0}'.format(new_arr4.shape))
print(new_arr4)
print('Shape of new_arr5: {0}'.format(new_arr5.shape))

Shape of new_arr4: (10, 10)
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
Shape of new_arr5: (100, 100)


### 2-1. Check

In [22]:
npz_1 = np.load('example_savez.npz')
npz_2 = np.load('example_savez_compressed.npz')

In [23]:
npz_1['my_arr1']

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [25]:
npz_2['my_arr4']

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [26]:
print(np.sum(npz_1['my_arr1'] - npz_2['my_arr4']))
npz_1['my_arr1'] - npz_2['my_arr4']

0


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
print(np.sum(npz_1['my_arr2'] - npz_2['my_arr5']))
npz_1['my_arr2'] - npz_2['my_arr5']

0


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [28]:
print(np.sum(npz_1['my_arr3'] - npz_2['my_arr6']))
npz_1['my_arr3'] - npz_2['my_arr6']

0


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### Conclusion: np.savez() and np.savez_compressed() are the same!!

## 3. [Day18]Numpy檔案輸入與輸出！
https://ithelp.ithome.com.tw/articles/10196167

### 3-1. save()

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.save('my_array',x)

### 3-2. load()

In [16]:
x_npz = np.load('my_array.npy')
x_npz

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x_npz - x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 3-3. savez()

In [18]:
aData = [1, 2, 3, 4, 5, 6]
bData = [7, 8, 9, 10, 11, 12]

np.savez('my_archive.npz', a=aData, b=bData)

In [19]:
myArch = np.load('my_archive.npz')

myArch['b']

array([ 7,  8,  9, 10, 11, 12])

In [20]:
myArch['a']

array([1, 2, 3, 4, 5, 6])

In [21]:
print(myArch['b'] - bData)
print(myArch['a'] - aData)

[0 0 0 0 0 0]
[0 0 0 0 0 0]
