# numpy.stack
https://numpy.org/doc/stable/reference/generated/numpy.stack.html#numpy.stack

In [1]:
import numpy as np

## 1. Examples 1

In [2]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays

[array([[-0.7023828 , -0.45494705,  0.48614511, -1.00793361],
        [ 0.33948546,  0.56553811,  1.01974953, -1.38843388],
        [-1.02529979, -0.27643638,  0.29683372, -1.45077964]]),
 array([[ 2.01910046, -1.31882958, -0.12317833, -0.83504207],
        [-0.08078266,  1.95663277, -1.06204748, -1.32483679],
        [-1.69391658,  0.56776613, -0.19940533, -0.67844339]]),
 array([[ 1.02184325, -0.0503627 ,  1.03732305, -1.89951151],
        [ 1.39100504, -0.23246053, -0.53583608,  0.50429974],
        [-1.37709898, -1.31980366,  0.32193089, -0.05212029]]),
 array([[-1.14770459,  1.22124717, -0.2634807 , -0.639932  ],
        [-0.16394151,  0.30817447,  0.45838035, -1.07182348],
        [ 0.1729361 ,  1.03779218,  0.19476423,  2.14912081]]),
 array([[ 0.77376215,  1.55181565, -0.03538139,  0.77876325],
        [ 0.7559586 , -0.5841453 ,  0.27190693, -0.63238529],
        [ 0.18539521,  0.29601877,  1.45501222,  0.02104568]]),
 array([[-0.40778334, -0.30419918, -1.24079135, -0.48693396]

In [3]:
arrays.shape

AttributeError: 'list' object has no attribute 'shape'

In [4]:
arrays[0].shape

(3, 4)

In [5]:
len(arrays)

10

In [6]:
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [7]:
arrays_stack0 = np.stack(arrays, axis=0)
arrays_stack0

array([[[-0.7023828 , -0.45494705,  0.48614511, -1.00793361],
        [ 0.33948546,  0.56553811,  1.01974953, -1.38843388],
        [-1.02529979, -0.27643638,  0.29683372, -1.45077964]],

       [[ 2.01910046, -1.31882958, -0.12317833, -0.83504207],
        [-0.08078266,  1.95663277, -1.06204748, -1.32483679],
        [-1.69391658,  0.56776613, -0.19940533, -0.67844339]],

       [[ 1.02184325, -0.0503627 ,  1.03732305, -1.89951151],
        [ 1.39100504, -0.23246053, -0.53583608,  0.50429974],
        [-1.37709898, -1.31980366,  0.32193089, -0.05212029]],

       [[-1.14770459,  1.22124717, -0.2634807 , -0.639932  ],
        [-0.16394151,  0.30817447,  0.45838035, -1.07182348],
        [ 0.1729361 ,  1.03779218,  0.19476423,  2.14912081]],

       [[ 0.77376215,  1.55181565, -0.03538139,  0.77876325],
        [ 0.7559586 , -0.5841453 ,  0.27190693, -0.63238529],
        [ 0.18539521,  0.29601877,  1.45501222,  0.02104568]],

       [[-0.40778334, -0.30419918, -1.24079135, -0.48693396]

In [8]:
arrays_stack0[0]

array([[-0.7023828 , -0.45494705,  0.48614511, -1.00793361],
       [ 0.33948546,  0.56553811,  1.01974953, -1.38843388],
       [-1.02529979, -0.27643638,  0.29683372, -1.45077964]])

In [9]:
arrays[0]

array([[-0.7023828 , -0.45494705,  0.48614511, -1.00793361],
       [ 0.33948546,  0.56553811,  1.01974953, -1.38843388],
       [-1.02529979, -0.27643638,  0.29683372, -1.45077964]])

In [10]:
arrays_stack0[0]-arrays[0]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
for i in range(10):
    print(np.sum(arrays_stack0[i]-arrays[i]))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [12]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [13]:
arrays_stack1 = np.stack(arrays, axis=1)
arrays_stack1

array([[[-0.7023828 , -0.45494705,  0.48614511, -1.00793361],
        [ 2.01910046, -1.31882958, -0.12317833, -0.83504207],
        [ 1.02184325, -0.0503627 ,  1.03732305, -1.89951151],
        [-1.14770459,  1.22124717, -0.2634807 , -0.639932  ],
        [ 0.77376215,  1.55181565, -0.03538139,  0.77876325],
        [-0.40778334, -0.30419918, -1.24079135, -0.48693396],
        [ 0.38529199, -1.0329774 ,  1.13547164,  1.32800157],
        [-0.1373168 ,  1.07504753,  0.7108573 ,  2.25552489],
        [ 0.57377328, -0.29788484,  0.9037411 ,  0.92082458],
        [ 0.22546989, -2.02416508, -0.32155525,  0.31639413]],

       [[ 0.33948546,  0.56553811,  1.01974953, -1.38843388],
        [-0.08078266,  1.95663277, -1.06204748, -1.32483679],
        [ 1.39100504, -0.23246053, -0.53583608,  0.50429974],
        [-0.16394151,  0.30817447,  0.45838035, -1.07182348],
        [ 0.7559586 , -0.5841453 ,  0.27190693, -0.63238529],
        [-1.54650259, -0.61697324,  0.18126111, -1.20230964],
      

In [14]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [15]:
arrays_stack2 = np.stack(arrays, axis=2)
arrays_stack2

array([[[-0.7023828 ,  2.01910046,  1.02184325, -1.14770459,
          0.77376215, -0.40778334,  0.38529199, -0.1373168 ,
          0.57377328,  0.22546989],
        [-0.45494705, -1.31882958, -0.0503627 ,  1.22124717,
          1.55181565, -0.30419918, -1.0329774 ,  1.07504753,
         -0.29788484, -2.02416508],
        [ 0.48614511, -0.12317833,  1.03732305, -0.2634807 ,
         -0.03538139, -1.24079135,  1.13547164,  0.7108573 ,
          0.9037411 , -0.32155525],
        [-1.00793361, -0.83504207, -1.89951151, -0.639932  ,
          0.77876325, -0.48693396,  1.32800157,  2.25552489,
          0.92082458,  0.31639413]],

       [[ 0.33948546, -0.08078266,  1.39100504, -0.16394151,
          0.7559586 , -1.54650259,  0.59907497,  0.53960315,
         -0.93930297,  1.68833264],
        [ 0.56553811,  1.95663277, -0.23246053,  0.30817447,
         -0.5841453 , -0.61697324,  0.45820684,  0.33325541,
         -0.02531685, -0.55314865],
        [ 1.01974953, -1.06204748, -0.53583608,  0

## 2. Example 2

In [16]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
ab_stack = np.stack((a, b))
ab_stack

array([[1, 2, 3],
       [2, 3, 4]])

In [17]:
ab_stack[1]

array([2, 3, 4])

In [18]:
ab_stack[1]-b

array([0, 0, 0])

In [19]:
ab_stack_m1 = np.stack((a, b), axis=-1)
ab_stack_m1

array([[1, 2],
       [2, 3],
       [3, 4]])

## 3. Test by myself

### 3-1. Test 1

In [20]:
c = np.array([3, 4, 5])
np.stack((a, b, c))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

### 3-2. Test 2

In [21]:
np.stack((a, b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
np.stack((a, b), axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [23]:
np.stack((a, b), axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [24]:
c = np.array([[1,2,11],[3,4,22]])
d = np.array([[5,6,33],[7,8,44]])
cd_stack0 = np.stack((c, d), axis=0)
print(cd_stack0.shape)
cd_stack0

(2, 2, 3)


array([[[ 1,  2, 11],
        [ 3,  4, 22]],

       [[ 5,  6, 33],
        [ 7,  8, 44]]])

In [25]:
cd_stack1 = np.stack((c, d), axis=1)
print(cd_stack1.shape)
cd_stack1

(2, 2, 3)


array([[[ 1,  2, 11],
        [ 5,  6, 33]],

       [[ 3,  4, 22],
        [ 7,  8, 44]]])

In [26]:
cd_stack2 = np.stack((c, d), axis=2)
print(cd_stack2.shape)
cd_stack2

(2, 3, 2)


array([[[ 1,  5],
        [ 2,  6],
        [11, 33]],

       [[ 3,  7],
        [ 4,  8],
        [22, 44]]])