# numpy.transpose
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html  
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html

In [1]:
import numpy as np

## 1. numpy.transpose
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

### 1-1. Example 1

In [2]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [3]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

### 1-2. Example 2

In [4]:
x = np.ones((1, 2, 3))
np.transpose(x, (1, 0, 2)).shape

(2, 1, 3)

In [5]:
print(x.shape)
x

(1, 2, 3)


array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
np.transpose(x, (1, 0, 2))

array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

### 1-3. Example 3

In [7]:
x = np.ones((2, 3, 4, 5))
np.transpose(x).shape

(5, 4, 3, 2)

In [8]:
x

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

## 2. numpy.ndarray.transpose
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html

In [9]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [10]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [11]:
a.transpose((1, 0))

array([[1, 3],
       [2, 4]])

In [12]:
a.transpose(1, 0)

array([[1, 3],
       [2, 4]])